//! WinRT toast notifications (Phase 4 Step 4.6).
//!
//! The Python backend never touches WinRT (`project_logic.md` §7): it emits
//! `toast.register` / `toast.cancel` / `toast.fire` / `toast.cancel_all`
//! **event** frames over stdio, the stdout reader (`backend::route_frame`)
//! routes any `toast.*` event here instead of forwarding it to the webview, and
//! this module drives `Windows.UI.Notifications`.
//!
//! `toast_id` is generated by the Python side (`IpcToastBridge`) and used
//! verbatim as the [`ScheduledToastNotification`] `Tag`, so cancel needs no
//! round-trip — it just names the same tag.
//!
//! **Same-notifier rule** (carried from Phase 1 Step 1.5b): every call uses one
//! `ToastNotifier` per process — held in a `thread_local` on the single stdout
//! reader thread that calls [`handle`], which also sidesteps the `!Send` COM
//! object.
//!
//! Live delivery needs a registered AUMID, which only exists once the app is
//! MSIX-packaged (Phase 5). On an unpackaged dev build `CreateToastNotifier`
//! may fail; every failure here is logged and swallowed so a missing toast
//! never breaks the reminder write on the Python side.

use serde_json::Value;

#[cfg(windows)]
mod winrt {
    use super::Value;
    use std::cell::RefCell;

    use windows::core::{Interface, HSTRING};
    use windows::Data::Xml::Dom::XmlDocument;
    use windows::Foundation::DateTime;
    use windows::UI::Notifications::{
        ScheduledToastNotification, ToastNotification, ToastNotificationManager, ToastNotifier,
    };

    const GROUP: &str = "mirrormind-reminders";
    // 100-ns ticks between 1601-01-01 (WinRT epoch) and 1970-01-01 (Unix epoch).
    const EPOCH_DELTA_TICKS: i64 = 11_644_473_600 * 10_000_000;

    thread_local! {
        static NOTIFIER: RefCell<Option<ToastNotifier>> = const { RefCell::new(None) };
    }

    fn with_notifier<T>(f: impl FnOnce(&ToastNotifier) -> windows::core::Result<T>) -> Option<T> {
        NOTIFIER.with(|slot| {
            let mut slot = slot.borrow_mut();
            if slot.is_none() {
                match ToastNotificationManager::CreateToastNotifier() {
                    Ok(n) => *slot = Some(n),
                    Err(e) => {
                        eprintln!("[mirrormind] toast: CreateToastNotifier failed ({e}) — no AUMID? (dev build)");
                        return None;
                    }
                }
            }
            match f(slot.as_ref().unwrap()) {
                Ok(v) => Some(v),
                Err(e) => {
                    eprintln!("[mirrormind] toast: WinRT call failed: {e}");
                    None
                }
            }
        })
    }

    fn toast_xml(body: &str) -> windows::core::Result<XmlDocument> {
        // ToastGeneric with a single text line; no actions (a reminder toast).
        let xml = format!(
            "<toast><visual><binding template=\"ToastGeneric\">\
             <text>MirrorMind reminder</text><text>{}</text>\
             </binding></visual></toast>",
            xml_escape(body)
        );
        let doc = XmlDocument::new()?;
        doc.LoadXml(&HSTRING::from(xml))?;
        Ok(doc)
    }

    fn xml_escape(s: &str) -> String {
        s.replace('&', "&amp;")
            .replace('<', "&lt;")
            .replace('>', "&gt;")
    }

    /// ISO-8601 (with offset) -> WinRT `DateTime`. `None` if unparseable.
    fn parse_delivery(iso: &str) -> Option<DateTime> {
        let odt = time::OffsetDateTime::parse(iso, &time::format_description::well_known::Rfc3339)
            .ok()?;
        let unix_ticks = (odt.unix_timestamp_nanos() / 100) as i64;
        Some(DateTime {
            UniversalTime: unix_ticks + EPOCH_DELTA_TICKS,
        })
    }

    fn field<'a>(frame: &'a Value, key: &str) -> Option<&'a str> {
        frame
            .pointer(&format!("/payload/params/{key}"))
            .and_then(Value::as_str)
    }

    pub fn handle(method: &str, frame: &Value) {
        match method {
            "toast.register" => {
                let (Some(id), Some(when), Some(body)) = (
                    field(frame, "toast_id"),
                    field(frame, "scheduled_time"),
                    field(frame, "body"),
                ) else {
                    eprintln!("[mirrormind] toast.register: missing fields");
                    return;
                };
                let Some(delivery) = parse_delivery(when) else {
                    eprintln!("[mirrormind] toast.register: bad scheduled_time {when:?}");
                    return;
                };
                with_notifier(|n| {
                    let xml = toast_xml(body)?;
                    let sched = ScheduledToastNotification::CreateScheduledToastNotification(
                        &xml, delivery,
                    )?;
                    sched.SetTag(&HSTRING::from(id))?;
                    sched.SetGroup(&HSTRING::from(GROUP))?;
                    n.AddToSchedule(&sched)
                });
            }
            "toast.cancel" => {
                let Some(id) = field(frame, "toast_id") else {
                    return;
                };
                remove_matching(|tag| tag == id);
            }
            "toast.cancel_all" => {
                // No bulk API — RemoveFromSchedule per id.
                remove_matching(|_| true);
            }
            "toast.fire" => {
                let Some(body) = field(frame, "body") else {
                    return;
                };
                with_notifier(|n| {
                    let xml = toast_xml(body)?;
                    let toast = ToastNotification::CreateToastNotification(&xml)?;
                    n.Show(&toast)
                });
            }
            _ => {}
        }
    }

    fn remove_matching(pred: impl Fn(&str) -> bool) {
        with_notifier(|n| {
            let scheduled = n.GetScheduledToastNotifications()?;
            let count = scheduled.Size()?;
            for i in 0..count {
                let item = scheduled.GetAt(i)?;
                let tag = item.Tag().unwrap_or_default().to_string();
                let group = item.Group().unwrap_or_default().to_string();
                if group == GROUP && pred(&tag) {
                    n.RemoveFromSchedule(&item)?;
                }
            }
            Ok(())
        });
    }

    // Keep the `Interface` import used (some `windows` versions need it in scope
    // for `.cast()`); harmless no-op otherwise.
    #[allow(dead_code)]
    fn _keep_interface_import(x: &XmlDocument) -> Option<XmlDocument> {
        x.cast().ok()
    }
}

/// Handle one `toast.*` event frame. Called only from `backend::route_frame` on
/// the stdout reader thread. No-op (with a log) off Windows.
#[cfg(windows)]
pub fn handle(method: &str, frame: &Value) {
    winrt::handle(method, frame);
}

#[cfg(not(windows))]
pub fn handle(method: &str, _frame: &Value) {
    eprintln!("[mirrormind] toast: {method} ignored (not Windows)");
}
